---
title: "Disconnected, Reconnect and Reload"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Disconnected, Reconnect and Reload}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Custom disconnected screen

Nobody likes it when an app stops responding. Traditionally, Shiny apps will be "grayed out". Since this doesn't provide a nice user experience, `{shinyMobile}` adds a custom disconnected screen. This screen (a toast) is displayed when the app is disconnected from the server.

TODO: shinylive example

```{r, eval = FALSE}
library(shiny)
library(shinyMobile)

shinyApp(
  ui = f7Page(
    options = list(dark = FALSE),
    title = "My app",
    f7SingleLayout(
      navbar = f7Navbar(
        title = "Custom disconnected screen",
        hairline = FALSE
      ),
      f7Block(
        f7Button(inputId = "disconnect",
                 label = "Disconnect me")
      )
    )
  ),
  server = function(input, output) {
    # set ignoreInit to avoid the observer being triggered after reconnect
    # this happens because of restoring the app's state
    observeEvent(input$disconnect, ignoreInit = TRUE, {
      print(input$disconnect)
      stop("Oops, I disconnected you!")
    })
  }
)
```

The user is given two options: either to **reconnect** or to **reload** the app. There's a subtle difference between the two, which is explained below.

## Reconnect

This button will attempt to reconnect to the server. If the server is not available, or encounters an error again, the custom disconnected screen will be displayed again.

<br>

When reconnecting, Shiny attempts to restore the app to its previous state. This means that the app will be in the same state as before the disconnection. In the above code, this means that the value of `input$disconnect` will be set to `1` again.

<br>

Note that the JS code behind the reconnect button ignores the user [reconnect setup](https://shiny.rstudio.com/articles/reconnecting.html) and proposes reconnecting regardless of the `session$allowReconnect` configuration. A solution is provided in the [Outstanding User Interfaces with Shiny](https://unleash-shiny.rinterface.com/mobile-going-further#enhance-the-disconnect-screen).

## Reload

The custom disconnected screen also includes a reload button. This button will reload the app (like hitting refresh in your browser). This is useful when the app is stuck in a loop and the reconnect button doesn't work. Compared to reconnecting, reloading will start from a clean slate: there's no restoring of values.

<br>

Note that when setting your app up to be a PWA, there's an `offline.html` asset generated when using `charpente::set_pwa()`. This page will be displayed when the user is offline. This page contains a reload button that will reload the app. It is not reconnecting.
